### PR TITLE
feat: unpack bootstrap using TypeScript for cross-platform compatibility

### PR DESCRIPTION
**Pull request by HRAshton**

### CODE REVIEW

**Comment by tmokmss** [comment]
Hi @HRAshton, thanks! I was not aware of this platform issue. I assumed these commands are executed inside the docker container, but yeah, the underlying NodejsFunction does [local bundling if esbuild is available locally](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs-readme.html#local-bundling), and it may not work on different shell or Windows environment.

So, another solution is to use [`forceDockerBundling` flag](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#forcedockerbundling), which forces bundling commands run in a container and become free from cross-platform issues. What do you think?

I'm afraid your solution may not work after npm publish because ts-node or unzipper are in dev dependencies. Also I'd like to keep dependencies as small as possible for maintenability.

**Comment by HRAshton** [comment]
Hmm.. Make sense, I'll try it, thank you

**Comment by tmokmss** [comment]
I guess something like this should work on Windows.

```ts
    new LlrtFunction(this, 'Handler', {
      entry: 'handler.ts',
      bundling: {
        forceDockerBundling: true,
      },
    });
```

Please let me know if it doesn't work. I don't have Windows environment in hand 🙏  Then we can update README to describe the workaround.

**Comment by tmokmss** [comment]
@HRAshton I updated the code to automatically set `forceDockerBundling: true` on Windows platform. b9e41f7 along with updating README. Let me know if you have further problem. Thanks again!

**Comment by HRAshton** [comment]
Yes, I just checked it out, works great) Thanks!

**Pull request closed without merging**
